import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";

/**
 * Figtree font configuration for UI text elements
 *
 * Primary sans-serif font used for body text, buttons, and interface elements.
 * Optimized for readability at various sizes with excellent character distinction.
 * Applied globally via CSS variable --font-sans for consistent theming.
 *
 * Font characteristics:
 * - Humanist sans-serif design with open forms and friendly appearance
 * - Excellent legibility at small sizes for dense UI content
 * - Warm, approachable aesthetic suitable for creative applications
 * - Variable font format with weight axis (100-900) for typographic flexibility
 *
 * Usage:
 * - Body text, paragraphs, labels, and descriptive content
 * - UI controls (buttons, inputs, menus)
 * - Headings at smaller sizes (h3-h6)
 *
 * @see https://fonts.google.com/specimen/Figtree
 */
const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

/**
 * Geist Sans font configuration for primary interface text
 *
 * Clean, geometric sans-serif optimized for UI readability and information density.
 * Used as the primary interface font with excellent legibility at small sizes.
 * Applied globally via CSS variable --font-geist-sans.
 *
 * Font characteristics:
 * - Neutral, geometric sans-serif with high x-height
 * - Optimized for screen rendering and UI contexts
 * - Distinct character forms to prevent misreading (e.g., I/l/1)
 * - Variable font format with weight axis (100-900)
 *
 * Usage:
 * - Primary body text and interface copy
 * - Data displays and information-dense contexts
 * - Secondary headings and section titles
 *
 * @see https://vercel.com/font
 */
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

/**
 * Geist Mono font configuration for monospace contexts
 *
 * Monospaced variant of Geist designed for code, technical content, and tabular data.
 * Features consistent character width for alignment and technical readability.
 * Applied globally via CSS variable --font-geist-mono.
 *
 * Font characteristics:
 * - Monospaced design with programmer-friendly character distinctions
 * - Clear differentiation between similar characters (0/O, 1/l/I, {}[]())
 * - Optimized spacing for code readability and terminal environments
 * - Variable font format with weight axis (100-900)
 *
 * Usage:
 * - Code snippets and syntax highlighting
 * - Variable names and technical identifiers in UI
 * - Tabular data requiring character alignment
 * - Debug output and console displays
 *
 * @see https://vercel.com/font
 */
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

/**
 * Application metadata configuration for SEO and social sharing
 *
 * Defines essential metadata consumed by search engines, social platforms, and browsers.
 * Values should be updated to reflect actual application identity before production deployment.
 *
 * Key properties:
 * - title: Primary display name shown in browser tabs and search results
 * - description: Concise summary of application purpose (150-160 characters ideal for SEO)
 * - Additional metadata (icons, theme-color, etc.) typically added in production builds
 *
 * Note: Current values are placeholder defaults from Create Next App template.
 * Should be replaced with application-specific values in production environments.
 *
 * @type {Metadata}
 * @see https://nextjs.org/docs/app/api-reference/functions/generate-metadata
 */
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * RootLayout component - Application root wrapper
 *
 * Serves as the foundational layout wrapper for the entire Next.js application.
 * Responsible for:
 * - Establishing global HTML document structure
 * - Injecting font configurations via CSS variables
 * - Applying global CSS styles and themes
 * - Setting language and base styling context
 * - Providing dark mode foundation via 'dark' class on body
 *
 * Architecture notes:
 * - Uses Next.js App Router layout convention (required file at app/layout.tsx)
 * - All page routes automatically inherit this layout structure
 * - Font variables injected via className prop on html/body elements
 * - Global styles imported from ./globals.css (resets, base styles, utilities)
 * - Dark mode enabled by default via 'dark' class on body element
 *
 * Font application strategy:
 * - figtree: Applied to html element as base sans-serif (--font-sans)
 * - geistSans: Available via --font-geist-sans CSS variable
 * - geistMono: Available via --font-geist-mono CSS variable for code contexts
 *
 * Theming:
 * - Dark mode foundation established via 'dark' class on body
 * - Light mode support possible via class toggling (not implemented in base layout)
 * - Color system defined in globals.css using CSS variables with dark/light variants
 *
 * Performance considerations:
 * - Font loading strategy handled automatically by Next.js Font Optimization
 * - Variable fonts reduce asset size compared to multiple static font files
 * - Critical CSS inlined via globals.css for fastest initial render
 *
 * @component
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Nested page content to render within layout
 * @returns {JSX.Element} Root HTML structure wrapping application content
 *
 * @example
 * // Automatic usage by Next.js App Router
 * // app/layout.tsx
 * export default function RootLayout({ children }) {
 *   return (
 *     <html lang="en">
 *       <body>{children}</body>
 *     </html>
 *   );
 * }
 *
 * @example
 * // Font usage in components via CSS variables
 * // components/CodeBlock.tsx
 * const CodeBlock = () => (
 *   <code className="font-mono font-geist-mono">
 *     local x = 10
 *   </code>
 * );
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={figtree.variable}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
            >
                {children}
            </body>
        </html>
    );
}